version: '3'

services:
  database:
    image: 'mysql:latest'
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABSE: db_demo
    ports:
      - '3306'

  phpmyadmin:
    image: phpmyadmin
    container_name: demo_phpmyadmin
    restart: always
    depends_on: 
      - database
    ports: 
      - 8080:80
    environment:
      PMA_HOST: database

  adminer:
    image: adminer
    restart: always
    ports: 
      - 8081:8080